---

- name: Include OS-specific variables.
  # yamllint disable-line rule:line-length
  include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"

- name: Install RedHat Software Collections
  when:
    - collections_enabled|bool
    - DTSVER|int > 6
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7
  include: 'install-rhscl.yml'
  tags:
    - clang
    - rhscl

- name: RedHat | Install LLVM toolset packages
  when:
    - ansible_os_family == 'RedHat'
  yum:
    name: "{{ llvm_toolset }}"
    state: present
    update_cache: true
  register: network_access
  until: network_access is success
  retries: 5
  delay: 2
  tags:
    - clang
    - rhscl

- name: RHSCL | Set llvm_install_dir
  when:
    - collections_enabled|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int < 8
  set_fact:
    llvm_install_dir: "/opt/rh/llvm-toolset-{{ DTSVER }}.0/root"
  tags:
    - clang
    - rhscl

- name: RHSCL | Enable LLVM toolset
  when:
    - collections_enabled|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int < 8
  file:
    src: "/opt/rh/llvm-toolset-{{ DTSVER }}.0/enable"
    path: /etc/profile.d/enable_llvm_toolset.sh
    state: link
  tags:
    - clang
    - rhscl


- name: Compile LLVM+CLang
  when: llvm_compilation|bool and ansible_os_family == 'RedHat'
  include: 'compile-llvm.yml'
  tags:
    - clang
    - compile

- name: LLVM | add environment variables to /etc/profile.d/llvm.sh
  become: true
  template:
    src: llvm.sh-template.j2
    dest: "/etc/profile.d/llvm.sh"
    mode: 0644
  tags:
    - clang
    - rhscl
...
